spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog?useSSL=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

logging:
  level:
    com.yvmoux.blog: info

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
