spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog?useSSL=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

logging:
  level:
    com.yvmoux.blog: info
    org.flywaydb: debug

ai:
  base-url: https://api.deepseek.com
  api-key:
  model: deepseek-chat
  max-tokens: 1024
  temperature: 0.3
  enabled: true

oss:
  qiniu:
    access-key-id:
    access-key-secret:
    bucket-name:
email:
  resend:
    api-key:

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  secret: ${JWT_SECRET:yblog}
  access-token-expiration: 300 # 5 min
  refresh-token-expiration: 86400 # 1 day